// ==UserScript==
// @name            Google.Translate Selector
// @version         2020.04.25
// @description     Выборка языков для Комикслейта и прочие улучшения
// @include         http*://translate.google.com*
// @author          Rainbow-Spike
// @namespace       https://greasyfork.org/users/7568
// @homepage        https://greasyfork.org/ru/users/7568-dr-yukon
// @icon            https://www.google.com/s2/favicons?domain=translate.google.com
// @grant           GM_addStyle
// ==/UserScript==

GM_addStyle(".page{max-width:99% !important;}body.with-lang-list .input{width:50%;} body.with-lang-list .ls-wrap{max-width:inherit;width:200%;} .language-list{border:1px solid #999;display:inline-flex !important;margin-bottom:0;padding-left:0;width:calc(50% - 2px);}" );
GM_addStyle(".language_list_languages{padding:3px !important;} .language-list-unfiltered-langs-sl_list,.language-list-unfiltered-langs-tl_list{display:flex;}" );
GM_addStyle(".language_list_section{display:flex;flex-flow:row wrap;} .language_list_item_wrapper{border:1px solid #ccc;border-radius:15px;width:max-content;max-width: 120px;}" );
GM_addStyle(".language_list_item_wrapper-az,.language_list_item_wrapper-sq,.language_list_item_wrapper-am,.language_list_item_wrapper-ar,.language_list_item_wrapper-hy,.language_list_item_wrapper-af,.language_list_item_wrapper-eu,.language_list_item_wrapper-bn,.language_list_item_wrapper-my,.language_list_item_wrapper-bs,.language_list_item_wrapper-cy,.language_list_item_wrapper-vi,.language_list_item_wrapper-haw,.language_list_item_wrapper-gl,.language_list_item_wrapper-ka,.language_list_item_wrapper-gu,.language_list_item_wrapper-zu,.language_list_item_wrapper-ig,.language_list_item_wrapper-yi,.language_list_item_wrapper-ga,.language_list_item_wrapper-is,.language_list_item_wrapper-yo,.language_list_item_wrapper-kk,.language_list_item_wrapper-kn,.language_list_item_wrapper-ca,.language_list_item_wrapper-ky,.language_list_item_wrapper-zh-TW,.language_list_item_wrapper-co,.language_list_item_wrapper-ht,.language_list_item_wrapper-ku,.language_list_item_wrapper-km,.language_list_item_wrapper-xh,.language_list_item_wrapper-lo,.language_list_item_wrapper-la,.language_list_item_wrapper-lv,.language_list_item_wrapper-lt,.language_list_item_wrapper-lb,.language_list_item_wrapper-mk,.language_list_item_wrapper-mg,.language_list_item_wrapper-ms,.language_list_item_wrapper-ml,.language_list_item_wrapper-mt,.language_list_item_wrapper-mi,.language_list_item_wrapper-mr,.language_list_item_wrapper-mn,.language_list_item_wrapper-ne,.language_list_item_wrapper-nl,.language_list_item_wrapper-no,.language_list_item_wrapper-or,.language_list_item_wrapper-pa,.language_list_item_wrapper-fa,.language_list_item_wrapper-ps,.language_list_item_wrapper-ro,.language_list_item_wrapper-rw,.language_list_item_wrapper-sm,.language_list_item_wrapper-ceb,.language_list_item_wrapper-sr,.language_list_item_wrapper-st,.language_list_item_wrapper-si,.language_list_item_wrapper-sd,.language_list_item_wrapper-sk,.language_list_item_wrapper-sl,.language_list_item_wrapper-so,.language_list_item_wrapper-sw,.language_list_item_wrapper-su,.language_list_item_wrapper-tg,.language_list_item_wrapper-th,.language_list_item_wrapper-ta,.language_list_item_wrapper-te,.language_list_item_wrapper-tk,.language_list_item_wrapper-tr,.language_list_item_wrapper-tt,.language_list_item_wrapper-uz,.language_list_item_wrapper-ug,.language_list_item_wrapper-ur,.language_list_item_wrapper-tl,.language_list_item_wrapper-fy,.language_list_item_wrapper-ha,.language_list_item_wrapper-hmn,.language_list_item_wrapper-hr,.language_list_item_wrapper-ny,.language_list_item_wrapper-cs,.language_list_item_wrapper-sv,.language_list_item_wrapper-sn,.language_list_item_wrapper-gd,.language_list_item_wrapper-et,.language_list_item_wrapper-jw,.language-list-search-box,.language-list-toolbar,.detect_language,.language_list_item_icon{display:none !important;}" );
GM_addStyle(".language_list_item_wrapper-be{order:0;}.language_list_item_wrapper-bg{order:1;}.language_list_item_wrapper-da{order:2;}.language_list_item_wrapper-de{order:3;}.language_list_item_wrapper-el{order:4;}.language_list_item_wrapper-en{order:5;}.language_list_item_wrapper-eo{order:6;}.language_list_item_wrapper-es{order:7;}.language_list_item_wrapper-fi{order:8;}.language_list_item_wrapper-fr{order:9;}.language_list_item_wrapper-iw{order:10;}.language_list_item_wrapper-hi{order:11;}.language_list_item_wrapper-hu{order:12;}.language_list_item_wrapper-id{order:13;}.language_list_item_wrapper-it{order:14;}.language_list_item_wrapper-ja{order:15;}.language_list_item_wrapper-ko{order:16;}.language_list_item_wrapper-pl{order:17;}.language_list_item_wrapper-pt{order:18;}.language_list_item_wrapper-ru{order:19;}.language_list_item_wrapper-uk{order:20;}.language_list_item_wrapper-zh-CN{order:21;}" );
